### ISSUE TITLE
Improve presentation

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/old-mixer-tales#1]
We'll definitely want to use something like git-book with some custom darker theme. It should be atmospheric enough.

**Comment by Minoru** [comment]
Black font on black background? Can't imagine anything more atmospheric than that.

**Comment by ForNeVeR** [comment]
What about purple on pink or maybe chtonic on octarin?

**Comment by Minoru** [comment]
I… I didn't know that those tales of yours will have _this_ kind of atmosphere…

Unstarred and unwatched the repo, unfollowed you, dropped out of the organization, in the process of deleting my GitHub account and terminating my contract with ISP.

**Comment by ForNeVeR** [comment]
That was a joke about colors btw. ~_~

**Comment by ForNeVeR** [comment]
Superseded by #3 and #4.
