### ISSUE TITLE
Need a license

### ISSUE THREAD

**Issue by Minoru** [ForNeVeR/old-mixer-tales#2]
Never ever post any creative output without clearly stating how it's licensed! A couple of jokes on XMPP is one thing, but anything bigger than that is far more serious.

I'd be willing to contribute if you use CC-BY or any stronger license :3

**Comment by ForNeVeR** [comment]
I still haven't posted anything but a couple of jokes from the XMPP chat. But I was thinking about a license, thank you for the reminder.

**Comment by ForNeVeR** [comment]
I think I've chosen [CC BY 4.0](http://creativecommons.org/licenses/by/4.0/). Will update the readme soon.

**Comment by Newlifer** [comment]
I second CC BY 4.0

**Comment by ForNeVeR** [comment]
> Will update the readme soon.

Soon means really soon, right?
