### ISSUE TITLE
Translate to INSTEAD

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/old-mixer-tales#4]
I think that the tales should be an interactive story based on [INSTEAD](https://instead.syscall.ru/ru/). We need to prepare set of Lua scripts to spin that up.
## Plan
- [x] #10: Initial high-level world details
- [x] ~~#9: S592 improvements~~
- [x] Consider using browser INSTEAD

**Comment by Newlifer** [comment]
I second this!

**Comment by Minoru** [comment]
Instead can be webhosted now; see [instead-js](https://github.com/instead-hub/instead-js). All the more reasons to move to it!

**Comment by ForNeVeR** [comment]
@Minoru https://tales.codingteam.org.ru/
